# Generated by Django 5.2.7 on 2025-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('faam_id', models.AutoField(primary_key=True, serialize=False)),
                ('faam_name', models.CharField(max_length=100)),
                ('faam_mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
